### ISSUE TITLE
Using annotations in a cucumber test environment with MockMvcSupport does not create a Principal in Spring Boot

### ISSUE THREAD

**Issue by eaudet** [ch4mpy/spring-addons#29]
**Describe the bug**
We have Keycloak configured in our Spring Boot micro-service. We use Cucumber to test our backend rest service endpoints. We use JWT tokens to secure endpoints. I use a very simple @WithMockKeycloakAuth({ "ROLE_user" }) annotation. When stepping in the controller, the Principal was not created (null). Hence, the annotation on a service method @RolesAllowed("user") fails. 

**Code sample**
1. failing test
```
@WithMockKeycloakAuth({ "ROLE_user" })
    public List<ProductLightDTO> securedProductSearch(ProductFilter filter, String username, String password) throws Exception {
        ObjectMapper objectMapper = new ObjectMapper();
        String body = objectMapper.writeValueAsString(filter);
        MvcResult result = api.perform(post("/products").contentType(APPLICATION_JSON_UTF8)
                .content(body)).andReturn();
        List<ProductLightDTO> productLightDTOS = Arrays.asList(objectMapper.readValue(result.getResponse().getContentAsString(), ProductLightDTO.class));
        return productLightDTOS;
    }
```
2. Component under test
```
@RestController
@RequestMapping("/products")
public class ProductController {

    private final ProductService productService;

    @PostMapping("")
    public List<ProductLightDTO> searchProducts(@RequestBody ProductFilter productFilter, Principal principal) {
        return productService.search(productFilter);
    }
```

The service method (never gets ther since Spring Security is doing it's job)

```
@Service
@Log4j2
public class ProductService {

    @RolesAllowed("user")
    public List<ProductLightDTO> search(ProductFilter productFilter) {
..
    }
```

3. spring-security configuration involved (runtime and tests)

Runtime config:

```
@Configuration
@EnableWebSecurity
@EnableGlobalMethodSecurity(jsr250Enabled = true)
public class WebSecurityConfig extends KeycloakWebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        super.configure(http);
        http.cors().and().authorizeRequests()
                .anyRequest()
                .authenticated()
                .and()
                .httpBasic();
        http.csrf().disable();
    }

    @Autowired
    public void configureGlobal(AuthenticationManagerBuilder auth) {
        KeycloakAuthenticationProvider keycloakAuthenticationProvider = keycloakAuthenticationProvider();
        keycloakAuthenticationProvider.setGrantedAuthoritiesMapper(new SimpleAuthorityMapper());
        auth.authenticationProvider(keycloakAuthenticationProvider);
    }

    @Bean
    @Override
    protected SessionAuthenticationStrategy sessionAuthenticationStrategy() {
        return new RegisterSessionAuthenticationStrategy(new SessionRegistryImpl());
    }

    @Bean
    public KeycloakConfigResolver KeycloakConfigResolver() {
        return new KeycloakSpringBootConfigResolver();
    }

}
```

Test config:
```
@Component
@Import({ ServletKeycloakAuthUnitTestingSupport.UnitTestConfig.class })
public class SearchApi {
...
    @Autowired
    MockMvcSupport api;

    @WithMockKeycloakAuth({ "ROLE_user" })
    public List<ProductLightDTO> securedProductSearch(ProductFilter filter) throws Exception {
        ObjectMapper objectMapper = new ObjectMapper();
        String body = objectMapper.writeValueAsString(filter);
        MvcResult result = api.perform(post("/products").contentType(APPLICATION_JSON_UTF8)
                .content(body)).andReturn();
        List<ProductLightDTO> productLightDTOS = Arrays.asList(objectMapper.readValue(result.getResponse().getContentAsString(), ProductLightDTO.class));
        return productLightDTOS;
    }
```

**Expected behavior**

I expect to find a Principal in the controler with a role "user".

**Comment by eaudet** [comment]
Both `@EnableWebSecurity` and `@EnableGlobalMethodSecurity ` are included as I wrote in my original issue. I will try to find a moment to build a project.

**Comment by eaudet** [comment]
Hi, I have jump to cucumber 7.0.0 (as mentionned) but still have the same error. The annotation @WithMockKeycloakAuth({"ROLE_user"}) is not injected in spring context. Here's the stack trace:

```
Step failed
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.security.authentication.AuthenticationCredentialsNotFoundException: An Authentication object was not found in the SecurityContext
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:77)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:167)
	at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:183)
	at com.c4_soft.springaddons.security.oauth2.test.mockmvc.MockMvcSupport.perform(MockMvcSupport.java:154)
```

**Comment by eaudet** [comment]
@mpkorstanje in order to make this `@WithMockKeycloakAuth `useful, it needs to be on the test method and not global on the class annotated `@CucumberContextConfiguration`. Otherwise you cannot test finegrained role base access to spring services. 

I found something interesting by adding a `RequestPostProcessor` including a principal and a role in the mockMvc. This actually injects a principal in spring security context and I am able to have a fully instantiated Principal object in my spring service. But the role is still not injected correctly. Maybe this can help?

```
MvcResult result = mockMvc.perform(post("/products").contentType(APPLICATION_JSON_UTF8)
                .content(body).with(authUtil.getRequestPostProcessor("fakeOwner", "ROLE_user"))).andReturn();
```

My authUtil class:

```
@Component
public class AuthUtil {

    public RequestPostProcessor getRequestPostProcessor(String ownerUuid, String userRole) {
        return mockHttpServletRequest -> {
            mockHttpServletRequest.setUserPrincipal(() -> ownerUuid);
            mockHttpServletRequest.addUserRole(userRole);
            return mockHttpServletRequest;

        };
    }
}

```

**Comment by ch4mpy** [comment]
@eaudet I have a workaround for you untill we find a way to have annotations working: use MockMvc post processor.

I just pushed a demo of that on [gh-29 branch](https://github.com/ch4mpy/spring-addons/tree/gh-29/spring-security-oauth2-test-webmvc-addons/src/test/java/com/c4_soft/springaddons/samples/webmvc/keycloak/cucumber)

This Cucumber test suite passes on my computer

**Comment by mpkorstanje** [comment]
It's not quite obvious but a cucumber scenario matches to a junit method. As if calling several step definition methods from a single test method. This means that if the JUnit method does something to setup authorization this must be reflected in the steps of the scenario. So the annotation is essentially an extra method call. 

This means that your workaround is infact the correct solution.

**Comment by ch4mpy** [comment]
That's what I'm working on.
It's pretty verbose and inconvenient.

**Comment by mpkorstanje** [comment]
You can get it pretty lean I think. 
	
```
withMockKeycloakAuth().authorities("USER").claims(OpenIdClaims.preferredUsername("ch4mpy"));
```

Of course you'd have to write the DSL for that but that's a one time thing.

**Comment by eaudet** [comment]
@ch4mpy and @mpkorstanje thanks for the analysis. Even if annotations are not available, using roles in the Scenario directly is even better. Thanks!
