### ISSUE TITLE
Seems only support JDK version 17+

### ISSUE THREAD

**Issue by ajay6uc** [ch4mpy/spring-addons#56]
**Seems only support JDK version 17+**
Tried with java 11 does not work, get following exception on startup.

Caused by: java.lang.UnsupportedClassVersionError: com/c4_soft/springaddons/security/oauth2/config/SpringAddonsSecurityProperties has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)

**Comment by ch4mpy** [comment]
yes, [as per the  README, Java 17 is required as minimum](https://github.com/ch4mpy/spring-addons/#java-version), as comming versions of spring framework.

**Comment by ch4mpy** [comment]
@ajay6uc I just released a `5.1.2-jdk1.8` version which should work with your JDK 11 and older spring-boot.

Refer to `jdk1.8` branch if you need samples (there could be subtle differences).
